### ISSUE TITLE
Snowing effect when player is standing on snow

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/seasonal_xmas#1]
Here's a possibly lightweight implementation:

- Check if a player is standing on snowy nodes (and maybe also if player is standing directly under the sky).
- If yes, attach a particle spawner to the player that creates the effect of snow.

**Comment by LoneWolfHT** [comment]
Could even just have snow fall very lightly around the map

**Comment by LoneWolfHT** [comment]
I like working with particles so you could probably assign me to this

**Comment by ClobberXD** [comment]
> Could even just have snow fall very lightly around the map

Is that possible without performance hits? Also, how would you factor in areas of the map that aren't directly exposed to the sky?

**Comment by LoneWolfHT** [comment]
> Is that possible without performance hits?

My smoke grenades probably pack a bigger punch than what I'm thinking of


> Also, how would you factor in areas of the map that aren't directly exposed to the sky?

As in the Caverns map?

**Comment by LoneWolfHT** [comment]
If I remove the particle on_collide then I can just spawn from the very top of the world and have it drop down. There will be a delay at the beginning of matches but the particles won't be very obvious when they are landing on the ground anyway

**Comment by ClobberXD** [comment]
> My smoke grenades probably pack a bigger punch than what I'm thinking of

Soo... what are you thinking of?

 > As in the Caverns map?

Yes, and also smaller areas covered on surface maps, like team bases on surface maps, areas underneath bridges, tunnels, etc.

**Comment by ClobberXD** [comment]
> If I remove the particle on_collide then I can just spawn from the very top of the world and have it drop down. There will be a delay at the beginning of matches but the particles won't be very obvious when they are landing on the ground anyway

1) Are they performant enough? Even if they don't make the server lag, they'll make the client's machine go on its knees, if particles spawn throughout the 220x220x140 region.
2) If you remove `on_collide`, how would the particles disappear when they hit nodes? How else would you implement the node-exposed-to-air detection logic if you're going to spawn particles throughout the map?

**Comment by LoneWolfHT** [comment]
>     1. Are they performant enough? Even if they don't make the server lag, they'll make the client's machine go on its knees, if particles spawn throughout the 220x220x140 region.

There will probably be a single particle per every 10x10 area of map. Depends on how it looks to me when I do it

>     2. If you remove `on_collide`, how would the particles disappear when they hit nodes? How else would you implement the node-exposed-to-air detection logic if you're going to spawn particles throughout the map?

Guess I should have said 'If I set the particle to remove itself upon collision'

**Comment by ClobberXD** [comment]
> Guess I should have said 'If I set the particle to remove itself upon collision'

Oh ok, I misunderstood. This sounds good...

> There will probably be a single particle per every 10x10 area of map. Depends on how it looks to me when I do it

Particles in MT are greatly inefficient. Even 1 particle in every 10 cubic nodes of the map might add up.

**Comment by ClobberXD** [comment]
On second thought, snowing only when standing on snow isn't realistic. It should snow everywhere. While snow on green grass will look weird, we'd be changing those textures anyway... right?

**Comment by LoneWolfHT** [comment]
> On second thought, snowing only when standing on snow isn't realistic. It should snow everywhere. While snow on green grass will look weird, we'd be changing those textures anyway... right?

Maybe... :thinking:
https://github.com/MT-CTF/seasonal_xmas/pull/3
